.vscode/settings.json, package-lock.json, package.json
=> sdk->0.253

package-lock.json, package.json
https://github.com/Microsoft/ConversationLearner-Samples/issues/193
=> 1350: Train Dialogs can't end on a non-terminal action

package-lock.json, package.json, src/app.ts, src/demos/demoHybrid.ts, src/demos/demoPizzaOrder.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialSessionCallbacks.ts
=> 1354 - ClientMemoryManager is no longer async

package-lock.json, package.json
=> 1357 API callback not keeping entity values

package-lock.json, package.json, src/demos/tutorialSessionCallbacks.ts
=> 1354: fix naming bug

package-lock.json, package.json, src/app.ts, src/demos/demoMultiCL.ts, src/demos/demoPasswordReset.ts, src/demos/demoPizzaOrder.ts, src/demos/demoStorage.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialHybrid.ts, src/demos/tutorialSessionCallbacks.ts
Added SessionEndState
Improve hybrid sample
=> feat: sessionendstate

package-lock.json, package.json, src/app.ts, src/demos/demoMultiCL.ts, src/demos/demoPasswordReset.ts, src/demos/demoPizzaOrder.ts, src/demos/demoStorage.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialHybrid.ts, src/demos/tutorialSessionCallbacks.ts, src/ui.ts, tsconfig.json
align with SDK and move towards single express server which allows us to consolidate to a single port for running the bot
| Type | Route |
| --- | --- |
| BOT | http://localhost:3978/api/messages |
| SDK | http://localhost:3978/sdk/* |
| Directline | http://localhost:3978/directline/* |
This eliminates issues with port conflicts and port synchronization.
=> feat: use express instead of restify

.env.example, README.md, package-lock.json, package.json, src/app.ts, src/config.ts, src/demos/demoMultiCL.ts, src/demos/demoPasswordReset.ts, src/demos/demoPizzaOrder.ts, src/demos/demoStorage.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialHybrid.ts, src/demos/tutorialSessionCallbacks.ts, src/dol.ts
chore: update to only add /sdk if development
docs: udpate .env.example and readme
=>  fix: use single express server for bot, sdk, and directline

package-lock.json, package.json
=> fix: context object not available to onsesionstart

package-lock.json, package.json
=> fix: ui app change impace emulator

package-lock.json, package.json
=> fix: remove invalid console error for mutex

package-lock.json, package.json
=> fix: modelId change while emulator running

package-lock.json, package.json
=> feat: ability to show version update banner

package-lock.json, package.json
LUIS no longer supports.  Will be adding back alternatives in Sept
=> fix: encyclopedia entity no longer supported

README.md
=> Fix table rendering issue in readme.md

package-lock.json, package.json
=> fix: missing await on initsessionasync

package-lock.json, package.json
=> fix: manual session timeout losing orgsessionid

package-lock.json, package.json
Fixed edge case where wrong model could be selected if running in emulator and changed .env model reference
=> fix: model selection in botstartsesssion

.vscode/launch.json, package-lock.json, package.json, src/demos/demoMultiCL.ts, src/demos/tutorialHybrid.ts
Required for running app with multiple models
=> fix: intrainingui checks appid

package-lock.json, package.json, src/demos/demoMultiCL.ts, src/demos/demoPasswordReset.ts, src/demos/demoPizzaOrder.ts, src/demos/demoStorage.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialHybrid.ts, src/demos/tutorialSessionCallbacks.ts, src/server.ts
=>  fix: add @types/node as dev dependency and use known port value instead of listener

package-lock.json, package.json, src/app.ts, src/demos/demoMultiCL.ts, src/demos/demoPasswordReset.ts, src/demos/demoPizzaOrder.ts, src/demos/demoStorage.ts, src/demos/demoVRAppLauncher.ts, src/demos/tutorialAPICalls.ts, src/demos/tutorialEntityDetectionCallback.ts, src/demos/tutorialHybrid.ts, src/demos/tutorialSessionCallbacks.ts, src/dol.ts, src/server.ts
This should make it more clear when server is configured in way where the /sdk is added and UI can communicate with it
=> Add more logging to clarify when /sdk or /directline is added

package-lock.json, package.json
=> feat: log rich edit

package-lock.json, package.json
=> feat: edit and scroll

package-lock.json
=> fix: sdk update

package-lock.json, package.json
2nd pass on Edit and Continue.  Improved buttons, bug fixes, etc
=> feat: edit continue

package-lock.json, package.json
=> feat: sdk to 306

package-lock.json, package.json
=> feat: form submit without entities

package-lock.json, package.json, src/demos/demoMultiCL.ts, src/demos/demoPizzaOrder.ts, src/demos/tutorialAPICalls.ts
1501 Render callback gives the wrong error when I edit memory in it
1500 Update samples to show arguments in render callbacks
=> fix: bugs 1501 1500

package-lock.json, package.json
=> feat: update to sdk 0.286

package-lock.json, package.json, src/demos/tutorialAPICalls.ts
=> feat: fix logicresult api tutorial

package-lock.json, package.json
=> feat: label entity conflict detection

package-lock.json, package.json, src/demos/demoMultiCL.ts, src/demos/tutorialHybrid.ts
=> feat: update bot builder version

package-lock.json, package.json
=> fix: entity passing in api callback

package-lock.json, package.json
Negative entity editing
API callback error handling
=> feat: sdk 293

package-lock.json, package.json, src/demos/demoPizzaOrder.ts
entity detection callback not call every time
update SDK for bug bash fixes
=> fix: pizza update

package.json
Pull master back into dev after release
=> Dev to master 200

.env.example, .travis.yml, README.md, appveyor.yml, package-lock.json, package.json, site/index.html, src/app.test.ts, src/app.ts, src/config.ts, src/demos/demoPizzaOrder.ts, src/server.ts, src/ui.ts
Merge develop into master to bring in latest changes.
=> Release - January 2019

package-lock.json, package.json
As talked about during meeting, necessary since UI currently uses this repo for testing.
=> Update SDK to version that exposes conflicts

package-lock.json, package.json
merging of dialogs
allow tags and descriptions on log dialogs
on dialog lists show user input list rather than just first / last
=> feat: dialog merging, grid user inptut list

package-lock.json, package.json
=> fix: sdk to 318.5

package-lock.json, package.json
=> fix: sdk to 353.13

package-lock.json, site/index.html
When serving bot on different for it would still say 3978 which was wrong.
=> Update default bot page to use port from URL

package-lock.json, package.json, src/app.ts
Ensure next merge of develop to master doesn't re-introduce the bug.
=> Update SDK on develop branch
